### ISSUE TITLE
Unable to Add custom application component 

### ISSUE THREAD

**Issue by shanurAnsari** [pfurini/cuba-component-forgot-password#1]
@pfurini  find the Log and screen 
[11:32:07.907] Cannot add application component it.nexbit.cuba.security.forgotpassword:nxsecfp-global:0.1.0
[11:32:39.285] Exception has been thrown by com.haulmont.studio.backend.p.d@427a5b:
[11:32:39.285] java.io.FileNotFoundException: Artifact it.nexbit.cuba.security.forgotpassword:nxsecfp-global:0.1.0 not found in the repositories:[https://repo.cuba-platform.com/content/groups/work, https://repo.cuba-platform.com/content/groups/premium, https://mvnrepository.com/artifact/net.java.dev.jets3t/jets3t]

 at com.haulmont.studio.backend.p.d.a(SourceFile:428)

 at com.haulmont.studio.backend.p.d.c(SourceFile:361)

 at com.haulmont.studio.backend.p.d.a(SourceFile:266)

 at com.haulmont.studio.ui.n.m.a(SourceFile:95)

 at com.haulmont.studio.ui.n.m.b(SourceFile:74)

 at com.haulmont.studio.ui.n.z.commit(SourceFile:209)

 at com.haulmont.studio.ui.common.b.buttonClick(SourceFile:75)

 at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.lang.reflect.Method.invoke(Method.java:498)

 at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)

 at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)

 at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)

 at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)

 at com.vaadin.ui.Button.fireClick(Button.java:377)

 at com.vaadin.ui.Button$1.click(Button.java:54)

 at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 at java.lang.reflect.Method.invoke(Method.java:498)

 ...
[11:32:39.288] Cannot add application component it.nexbit.cuba.security.forgotpassword:nxsecfp-global:0.1.0
Messages
Clear
![capture](https://user-images.githubusercontent.com/32862274/31703123-a29e95ac-b3f8-11e7-9dcd-0fa2c42c018c.PNG)

**Comment by pfurini** [comment]
that's a gradle.build misconfiguration, closing as invalid
